### ISSUE TITLE
Enable Zookeeper REST server

### ISSUE THREAD

**Issue by danieltardon** [keedio/buildoop#26]
Zookeeper package does not include Zookeeper REST Server. 

It would be fine to include it in order to access to its functionality from HUE.

Since HUE 3 there is an enhanced Zookeeper app that needs the Zookeeper REST server to be running (by default in the same server than Zookeepet itself) and listening at 9998 port (by default) to access the Znodes hierarchy.

From a complete source package, after you build it, you can start the REST service as follows:
cd src/contrib/rest
nohup ant run&

I've tested it manually with Zookeeper 3.4.5 and Hue 3.5.0 versions.

Zookeeper REST Service --> https://github.com/apache/zookeeper/tree/trunk/src/contrib/rest

HUE 3 announcement and setup instructions --> http://gethue.tumblr.com/post/67482299450/new-zookeeper-browser-app

**Comment by javiroman** [comment]
The package must be proved in run time, this task is pending.

**Comment by javiroman** [comment]
Starting error in /var/log/zookeeper/zookeeper-rest.log:

Starting ZooKeeper REST Gateway
java  -cp /usr/lib/zookeeper-rest/zookeeper-*.jar:/usr/lib/zookeeper-rest/lib/zookeeper-dev-rest.jar:/usr/lib/zookeeper-rest/lib/zookeeper-3.4.5-rest.jar:/usr/lib/zookeeper-rest/lib/stax-api-1.0-2.jar:/usr/lib/zookeeper-rest/lib/stax-api-1.0.1.jar:/usr/lib/zookeeper-rest/lib/slf4j-log4j12-1.6.1.jar:/usr/lib/zookeeper-rest/lib/slf4j-api-1.6.1.jar:/usr/lib/zookeeper-rest/lib/servlet-api-2.5.jar:/usr/lib/zookeeper-rest/lib/log4j-1.2.15.jar:/usr/lib/zookeeper-rest/lib/jsr311-api-1.1.1.jar:/usr/lib/zookeeper-rest/lib/jettison-1.1.jar:/usr/lib/zookeeper-rest/lib/jersey-server-1.1.5.1.jar:/usr/lib/zookeeper-rest/lib/jersey-json-1.1.5.1.jar:/usr/lib/zookeeper-rest/lib/jersey-core-1.1.5.1.jar:/usr/lib/zookeeper-rest/lib/jaxb-impl-2.1.12.jar:/usr/lib/zookeeper-rest/lib/jaxb-api-2.1.jar:/usr/lib/zookeeper-rest/lib/jackson-core-asl-1.1.1.jar:/usr/lib/zookeeper-rest/lib/grizzly-utils-1.9.8.jar:/usr/lib/zookeeper-rest/lib/grizzly-servlet-webserver-1.9.8.jar:/usr/lib/zookeeper-rest/lib/grizzly-rcm-1.9.8.jar:/usr/lib/zookeeper-rest/lib/grizzly-portunif-1.9.8.jar:/usr/lib/zookeeper-rest/lib/grizzly-http-servlet-1.9.8.jar:/usr/lib/zookeeper-rest/lib/grizzly-http-1.9.8.jar:/usr/lib/zookeeper-rest/lib/grizzly-framework-1.9.8.jar:/usr/lib/zookeeper-rest/lib/asm-3.1.jar:/usr/lib/zookeeper-rest/lib/activation-1.1.jar:/etc/zookeeper/conf/rest:  org.apache.zookeeper.server.jersey.RestMain
Starting grizzly ...
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/zookeeper/Watcher
        at org.apache.zookeeper.server.jersey.RestMain.start(RestMain.java:60)
        at org.apache.zookeeper.server.jersey.RestMain.main(RestMain.java:121)
Caused by: java.lang.ClassNotFoundException: org.apache.zookeeper.Watcher
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 2 more

**Comment by javiroman** [comment]
Fixed and tested.
